backend/controllers/ModuleController.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @copyright Copyright (c) 2015 Anil Chaudhari
 * @license http://www.anilchaudhari.com.nplicense/
 */

namespace backend\controllers;

use common\components\Json;
use common\models\Module;
use common\models\search\Module as ModuleSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * Class ModuleController, controlling the actions for Module model.
 *
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @since 0.2.0
 */
class ModuleController extends Controller
{
    private $_dir;
    private $_tmp;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'view', 'delete', 'bulk-action'],
                        'allow' => true,
                        'roles' => ['administrator'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Module models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ModuleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Module model.
     * Module zip uploaded to temporary directory and extracted there.
     * Check the module directory and move the first directory of the extracted module.
     * If the module configuration is valid, save the module, if not remove the module.
     * If creation is successful, the browser will be redirected to the 'index' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $errors = [];
        $model = new Module(['scenario' => 'create']);

        if (!is_dir($this->_dir)) {
            FileHelper::createDirectory($this->_dir, 0755);
        }

        if (!is_dir($this->_tmp)) {
            FileHelper::createDirectory($this->_tmp, 0755);
        }

        if (($model->file = UploadedFile::getInstance($model, 'file')) && $model->validate(['file'])) {
            $tmpPath = $this->_tmp . $model->file->name;

            if (!$model->file->saveAs($tmpPath)) {
                return $this->render('create', [
                    'model' => $model,
                    'error' => [Yii::t('app', 'Failed to move uploaded file.')],
                ]);
            }

            $zipArchive = new \ZipArchive();
            $zipArchive->open($tmpPath);

            if (!$zipArchive->extractTo($this->_tmp)) {
                $zipArchive->close();
                FileHelper::removeDirectory($this->_tmp);

                return $this->render('create', [
                    'model' => $model,
                    'error' => [Yii::t('app', 'Failed to extract file.')],
                ]);
            }

            $baseDir = substr($zipArchive->getNameIndex(0), 0, strpos($zipArchive->getNameIndex(0), '/'));
            $zipArchive->close();
            unlink($tmpPath);
            $configPath = $this->_tmp . $baseDir . '/config/main.php';

            if (!is_file($configPath)) {
                FileHelper::removeDirectory($this->_tmp);

                return $this->render('create', [
                    'model' => $model,
                    'error' => [Yii::t('app', 'File configuration does not exist.')],
                ]);
            }

            $config = require($configPath);
            $model->setAttributes($config);
            $model->setAttributes(['directory' => $baseDir, 'status' => Module::STATUS_NOT_ACTIVE]);

            if ($model->validate(['directory'])) {
                rename($this->_tmp . $baseDir, $this->_dir . $baseDir);
            }

            FileHelper::removeDirectory($this->_tmp);
            $frontendClass = ArrayHelper::getValue($model->config, 'frontend.class', false);
            $backendClass = ArrayHelper::getValue($model->config, 'backend.class', false);

            if (!($frontendClass || $backendClass)) {
                $errors[] = Yii::t('app', 'Invalid config.');
            }

            if ($backendClass && !class_exists($backendClass)) {
                $errors[] = Yii::t('app', 'Invalid backend config.');
            }

            if ($frontendClass && !class_exists($frontendClass)) {
                $errors[] = Yii::t('app', 'Invalid frontend config.');
            }

            $model->config = Json::encode($model->config);

            if (!$errors && $model->validate(['name', 'title', 'config', 'directory']) && $model->save(false)) {
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Module successfully installed'));

                return $this->redirect(['index']);
            } else {
                if (!$model->hasErrors('directory')) {
                    FileHelper::removeDirectory($this->_dir . $baseDir);
                }

                $errors = ArrayHelper::merge($errors, $model->getFirstErrors());
            }
        }

        return $this->render('create', [
            'model' => $model,
            'error' => $errors,
        ]);
    }

    /**
     * Updates an existing Module model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->config = Json::encode($model->config);
            if ($model->save()) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Module model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Deletes an existing Module model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $path = Yii::getAlias($this->_dir . $model->directory);

        // Delete module and its directory
        if ($model->delete()) {
            FileHelper::removeDirectory($path);
        }

        return $this->redirect(['index']);
    }

    /**
     * Bulk action for Module triggered when button 'Apply' clicked.
     * The action depends on the value of the dropdown next to the button.
     * Only accept POST HTTP method.
     */
    public function actionBulkAction()
    {
        if (Yii::$app->request->post('action') === 'active') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $this->findModel($id)->updateAttributes(['status' => Module::STATUS_ACTIVE]);
            }
        } elseif (Yii::$app->request->post('action') === 'not-active') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $this->findModel($id)->updateAttributes(['status' => Module::STATUS_NOT_ACTIVE]);
            }
        } elseif (Yii::$app->request->post('action') === 'deleted') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $path = Yii::getAlias($this->_dir . $model->directory);
                if ($model->delete()) {
                    FileHelper::removeDirectory($path);
                }
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $this->_dir = Yii::getAlias('@modules/');
            $this->_tmp = Yii::getAlias('@common/tmp/modules/');

            return true;
        }

        return false;
    }

    /**
     * Finds the Module model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     * @return Module the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Module::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/controllers/UserController.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @copyright Copyright (c) 2015 Anil Chaudhari
 * @license http://www.anilchaudhari.com.nplicense/
 */

namespace backend\controllers;

use common\models\search\User as UserSearch;
use common\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * UserController, controlling the actions for User model.
 *
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @since 0.1.0
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'bulk-action'],
                        'allow' => true,
                        'roles' => ['administrator'],
                    ],
                    [
                        'actions' => ['profile', 'view', 'reset-password'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-action' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        // Set scenario to register, so that the password is required
        $model = new User(['scenario' => 'register']);

        if ($model->load(Yii::$app->request->post())) {
            $model->generateAuthKey();
            $model->setPassword($model->password);
            if ($model->save()) {
                Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $model->id);

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @throws \yii\web\ForbiddenHttpException
     * @throws \yii\web\NotFoundHttpException
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $this->checkPermission($model);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->authManager->revokeAll($id);
            Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $id);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @throws \Exception
     * @throws \yii\web\ForbiddenHttpException
     * @throws \yii\web\NotFoundHttpException
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $this->checkPermission($model);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Bulk action for User triggered when button 'Apply' clicked.
     * The action depends on the value of the dropdown next to the button.
     * Only accept POST HTTP method.
     */
    public function actionBulkAction()
    {
        if (Yii::$app->request->post('action') === 'active') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $model->updateAttributes(['status' => User::STATUS_ACTIVE]);
            }
        } elseif (Yii::$app->request->post('action') === 'not-active') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $this->checkPermission($model);
                $model->updateAttributes(['status' => User::STATUS_NOT_ACTIVE]);
            }
        } elseif (Yii::$app->request->post('action') === 'removed') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $this->checkPermission($model);
                $model->updateAttributes(['status' => User::STATUS_REMOVED]);
            }
        } elseif (Yii::$app->request->post('action') === 'deleted') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $this->checkPermission($model);
                $model->delete();
            }
        } elseif (Yii::$app->request->post('action') === 'changerole') {
            foreach (Yii::$app->request->post('ids', []) as $id) {
                $model = $this->findModel($id);
                $this->checkPermission($model);
                Yii::$app->authManager->revokeAll($id);
                Yii::$app->authManager->assign(Yii::$app->authManager->getRole(Yii::$app->request->post('role')), $id);
            }
        }
    }

    /**
     * Update the user data for the user who has logged in.
     *
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionProfile()
    {
        $model = $this->findModel(Yii::$app->user->id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password for logged user.
     * It requires three inputs from users to reset password, they are the old password, new password, and repeat password.
     * The old password will be checked by User::passwordValidation.
     *
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionResetPassword()
    {
        $model = $this->findModel(Yii::$app->user->id);
        $model->setScenario('resetPassword');

        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->password);
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('reset-password', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @param $model User
     * @throws ForbiddenHttpException
     */
    protected function checkPermission($model)
    {
        if (!$model->checkPermission()) {
            throw new ForbiddenHttpException(Yii::t('app', 'You are not allowed to perform this action.'));
        }
    }
}

backend/views/layouts/blank.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use backend\assets\AppAsset;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $content string */

// Favicon
$this->registerLinkTag(['rel' => 'icon', 'href' => Yii::getAlias('@web/favicon.ico'), 'type' => 'image/x-icon']);

AppAsset::register($this);
backend\assets\ShowLoadingAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="<?= ArrayHelper::getValue(Yii::$app->params, 'bodyClass', 'skin-blue sidebar-mini') ?>">
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main-footer.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

/* @var $this yii\web\View */
?>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b><?= Yii::powered() ?></b>
    </div>
    <strong>
        Copyright &copy; <?= date('Y') ?> <a href="http://www.anilchaudhari.com.np/" target="_blank">Anil Chaudhari</a>.
    </strong>
    All rights reserved.
</footer>

backend/views/layouts/main-header.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use cebe\gravatar\Gravatar;
use yii\helpers\Html;

/* @var $this yii\web\View */
?>
<header class="main-header">
    <a href="<?= Yii::$app->urlManagerFront->createUrl(['/site/index']) ?>" class="logo">
        <span class="logo-mini"><?= Html::img(Yii::getAlias('@web/img/logo-mini.png')) ?></span>
        <span class="logo-lg"><b>Admin</b> Panel</span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <?php if (!Yii::$app->user->isGuest): ?>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?= Gravatar::widget([
                                'email' => Yii::$app->user->identity->email,
                                'options' => ['alt' => 'Gravatar 25', 'class' => 'user-image'],
                                'size' => 25,
                            ]) ?>
                            <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <?= Gravatar::widget([
                                    'email' => Yii::$app->user->identity->email,
                                    'options' => ['alt' => 'Gravatar 84', 'class' => 'img-circle'],
                                    'size' => 84,
                                ]) ?>
                                <p>
                                    <?= Yii::$app->user->identity->username ?>
                                    <small>
                                        <?= Yii::t('app', 'Member since {date}', [
                                            'created_at' => Yii::$app
                                                ->formatter
                                                ->asDate(Yii::$app->user->identity->created_at, 'php:F d, Y'),
                                        ]) ?>
                                    </small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <?= Html::a(
                                        Yii::t('app', 'Profile'),
                                        ['/user/profile'],
                                        ['class' => 'btn btn-default btn-flat']
                                    ) ?>
                                </div>
                                <div class="pull-right">
                                    <?= Html::a(
                                        Yii::t('app', 'Sign Out'),
                                        ['/site/logout'],
                                        ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']
                                    ) ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                <?php endif ?>
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/main-sidebar.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use cebe\gravatar\Gravatar;
use codezeen\yii2\adminlte\widgets\Menu;
use common\models\Option;
use common\models\PostType;
use common\models\VideoType;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
?>

<aside class="main-sidebar">
    <section class="sidebar">

        <?php if (!Yii::$app->user->isGuest): ?>
            <div class="user-panel">
                <div class="pull-left image">
                    <?= Gravatar::widget([
                        'email' => Yii::$app->user->identity->email,
                        'options' => ['alt' => 'Gravatar 45', 'class' => 'img-circle'],
                        'size' => 45,
                    ]) ?>
                </div>
                <div class="pull-left info">
                    <p><?= Yii::$app->user->identity->username ?></p>
                    <?= Html::a(
                        '<i class="fa fa-circle text-success"></i>' . Yii::t('app', 'Online'),
                        ['/user/profile']
                    ) ?>
                </div>
            </div>
        <?php endif ?>

        <?php
        $adminMenu[0] = [
            'label' => Yii::t('app', 'MAIN NAVIGATION'),
            'options' => ['class' => 'header'],
            'template' => '{label}',
        ];
        $adminMenu[1] = [
            'label' => Yii::t('app', 'Dashboard'),
            'icon' => 'fa fa-dashboard',
            'url' => ['/site/index']
        ];

        $adminMenu[2] = [
            'label' => Yii::t('app', 'Emails'),
            'icon' => 'fa fa-envelope',
            'url' => ['/contact/index']
        ];
        
        $adminMenu[30] = [
            'label' => Yii::t('app', 'Modules'),
            'icon' => 'fa fa-laptop',
            'items' => [
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'All Modules'),
                    'url' => ['/module/index'],
                ],
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'Add New Module'),
                    'url' => ['/module/create'],
                ],
            ],
            'visible' => Yii::$app->user->can('administrator'),
        ];
        
        $adminMenu[60] = [
            'label' => Yii::t('app', 'Users'),
            'icon' => 'fa fa-user',
            'items' => [
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'All Users'),
                    'url' => ['/user/index'],
                    'visible' => Yii::$app->user->can('administrator'),
                ],
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'Add New User'),
                    'url' => ['/user/create'],
                    'visible' => Yii::$app->user->can('administrator'),
                ],
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'My Profile'),
                    'url' => ['/user/profile'],
                    'visible' => Yii::$app->user->can('subscriber'),
                ],
                [
                    'icon' => 'fa fa-circle-o',
                    'label' => Yii::t('app', 'Reset Password'),
                    'url' => ['/user/reset-password'],
                    'visible' => Yii::$app->user->can('subscriber'),
                ],
            ],
        ];
        $adminMenu = ArrayHelper::merge($adminMenu, Option::getMenus(70));

        if ($userAdminMenu = ArrayHelper::getValue(Yii::$app->params, 'adminMenu', [])) {
            $adminMenu = ArrayHelper::merge($adminMenu, $userAdminMenu);
        }

        ksort($adminMenu);
        echo Menu::widget(['items' => $adminMenu]);
        ?>

    </section>
</aside>

backend/views/layouts/main.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use codezeen\yii2\adminlte\widgets\Alert;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $content string */
?>
<?php $this->beginContent('@app/views/layouts/blank.php') ?>
<div class="wrapper">
    <?= $this->render('main-header') ?>
    <?= $this->render('main-sidebar') ?>
    <div class="content-wrapper">
        <section class="content-header">
            <h1><?= $this->title ?></h1>

            <?= Breadcrumbs::widget([
                'homeLink' => [
                    'label' => Html::a(
                        '<i class="fa fa-dashboard"></i> ' . Yii::t('app', 'Home'),
                        Yii::$app->homeUrl
                    ),
                ],
                'encodeLabels' => false,
                'links' => ArrayHelper::getValue($this->params, 'breadcrumbs', []),
            ]) ?>
        </section>
        <section class="content clearfix">
            <?= Alert::widget() ?>
            <?= $content ?>
        </section>
    </div>
    <?= $this->render('main-footer') ?>
</div>
<?php $this->endContent() ?>