backend/controllers/SiteController.php
<?php
/**
 * @link      http://www.anilchaudhari.com.np/
 * @copyright Copyright (c) 2015 Anil Chaudhari
 * @license   http://www.anilchaudhari.com.nplicense/
 */

namespace backend\controllers;

use common\models\LoginForm;
use common\models\Option;
use common\models\PasswordResetRequestForm;
use common\models\ResetPasswordForm;
use common\models\SignupForm;
use common\models\User;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * Site controller.
 *
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @since 0.1.0
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'login',
                            'request-password-reset',
                            'reset-password',
                            'forbidden',
                            'not-found',
                            'terms',
                        ],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'error'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'matchCallback' => function () {
                            return Option::get('allow_signup') && Yii::$app->user->isGuest;
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Show user count, post count, post-comment count on index (dashboard).
     *
     * @return string
     */
    public function actionIndex()
    {
        // Get list User model
        $userQuery = User::find()->andWhere(['status' => '10']);
        $userCloneQuery = clone $userQuery;
        $userCount = $userCloneQuery->count();
        $users = $userQuery->limit(8)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('index', [
            'users' => $users,
            'userCount' => $userCount,
        ]);
    }

    /**
     * Show login page and process login page.
     *
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        // Set layout and bodyClass for login-page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'login-page';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout for current user and redirect to home of backend.
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Show signup for guest to register on site while Option::get('allow_signup') is true.
     *
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        // Set layout and body class of register-page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'register-page';
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Generate and send token to user's email for resetting password.
     *
     * @return string|\yii\web\Response
     */
    public function actionRequestPasswordReset()
    {
        // Change layout and body class of register page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'register-page';
        $model = new PasswordResetRequestForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash(
                    'error',
                    'Sorry, we are unable to reset password for email provided.'
                );
            }
        }

        return $this->render('request-password-reset-token', [
            'model' => $model,
        ]);
    }

    /**
     * Show reset password. It requires param $token that generated on actionRequestPasswordReset which is sent to
     * user's email.
     *
     * @param $token
     * @return string|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        // Change layout and body class of reset password page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'register-page';

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('reset-password', [
            'model' => $model,
        ]);
    }

    /**
     * Render term and condition
     */
    public function actionTerms()
    {
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'skin-blue layout-boxed sidebar-mini';

        return $this->render('terms');
    }

    /**
     * @throws \yii\web\ForbiddenHttpException
     */
    public function actionForbidden()
    {
        throw new ForbiddenHttpException(Yii::t('app', 'You are not allowed to perform this action.'));
    }

    /**
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionNotFound()
    {
        throw new NotFoundHttpException(Yii::t('app', 'Page not found'));
    }
}

backend/controllers/WidgetController.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @copyright Copyright (c) 2015 Anil Chaudhari
 * @license http://www.anilchaudhari.com.nplicense/
 */

namespace backend\controllers;

use backend\components\Json;
use common\models\Widget;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * WidgetController, controlling the actions for Widget model.
 *
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @since 0.2.0
 */
class WidgetController extends Controller
{
    /**
     * @var string Path to widget directory.
     */
    private $_dir;

    /**
     * @var string Path to temporary directory of widget.
     */
    private $_tmp;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'delete',
                            'ajax-activate',
                            'ajax-update',
                            'ajax-delete',
                            'ajax-save-order',
                        ],
                        'allow'   => true,
                        'roles'   => ['administrator'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'ajax-activate' => ['post'],
                    'ajax-update'   => ['post'],
                    'ajax-delete'   => ['post'],
                ],
            ],
        ];
    }

    /**
     * Scan widget directory to get list of all available widgets and list all active widgets.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $config = [];
        $active = [];
        $available = [];
        $spaces = ArrayHelper::getValue(Yii::$app->params, 'widget', []);

        if (!is_dir($this->_dir)) {
            FileHelper::createDirectory($this->_dir, 0755);
        }

        foreach (scandir($this->_dir) as $widget) {
            if (is_dir($this->_dir . $widget) && $widget !== '.' && $widget !== '..') {
                $configPath = $this->_dir . $widget . '/config/main.php';
                if (is_file($configPath)) {
                    $config = require($configPath);
                    $config['directory'] = $widget;
                }
                $available[$widget] = $config;
            }
        }

        foreach ($spaces as $space) {
            $model = Widget::find()
                ->where(['location' => $space['location']])
                ->orderBy(['order' => SORT_ASC])
                ->all();
            $active[$space['location']] = $model;
        }

        return $this->render('index', [
            'active' => $active,
            'available' => $available,
            'spaces' => $spaces,
        ]);
    }

    /**
     * Register new widget.
     * Widget zip uploaded to temporary directory and extracted there.
     * Check the widget directory and move the first directory of the extracted widget.
     * If the widget configuration is valid, save the widget, if not remove the widget.
     * If registration is successful, the browser will be redirected to the 'index' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $errors = [];
        $model = new Widget(['scenario' => 'upload']);

        if (!is_dir($this->_tmp)) {
            FileHelper::createDirectory($this->_tmp, 0755);
        }

        if (!is_dir($this->_dir)) {
            FileHelper::createDirectory($this->_dir, 0755);
        }

        if (($model->file = UploadedFile::getInstance($model, 'file')) && $model->validate(['file'])) {
            $tmpPath = $this->_tmp . $model->file->name;

            if (!$model->file->saveAs($tmpPath)) {
                return $this->render('create', [
                    'model' => $model,
                    'errors' => [Yii::t('app', 'Failed to move uploaded file')],
                ]);
            }

            $zipArchive = new \ZipArchive();
            $zipArchive->open($tmpPath);

            if (!$zipArchive->extractTo($this->_tmp)) {
                $zipArchive->close();
                FileHelper::removeDirectory($this->_tmp);

                return $this->render('create', [
                    'model' => $model,
                    'errors' => [Yii::t('app', 'Failed to extract file.')],
                ]);
            }

            $baseDir = substr($zipArchive->getNameIndex(0), 0, strpos($zipArchive->getNameIndex(0), '/'));
            $zipArchive->close();
            $configPath = $this->_tmp . $baseDir . '/config/main.php';

            if (!is_file($configPath)) {
                FileHelper::removeDirectory($this->_tmp);

                return $this->render('create', [
                    'model' => $model,
                    'errors' => [Yii::t('app', 'File configuration does not exist.')],
                ]);
            }

            $config = require($configPath);

            if (is_dir($this->_dir . $baseDir)) {
                $errors['dirExist'] = Yii::t('app', 'Widget with the same directory already exist.');
            } else {
                rename($this->_tmp . $baseDir, $this->_dir . $baseDir);
            }

            FileHelper::removeDirectory($this->_tmp);

            if (!isset($config['title'])
                || !(isset($config['config']['class']) && class_exists($config['config']['class']))
            ) {
                $errors[] = Yii::t('app', 'Invalid configuration.');
            }

            if (!$errors) {
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Widget successfully installed.'));

                return $this->redirect(['index']);
            } else {
                if (!ArrayHelper::getValue($errors, 'dirExist')) {
                    FileHelper::removeDirectory($this->_dir . $baseDir);
                }

                $errors = ArrayHelper::merge($errors, $model->getFirstErrors());
            }
        }

        return $this->render('create', [
            'model' => $model,
            'errors' => $errors,
        ]);
    }

    /**
     * Delete widget and activated widgets.
     *
     * @param $id string
     *
     * @return \yii\web\Response
     */
    public function actionDelete($id)
    {
        FileHelper::removeDirectory($this->_dir . $id);
        Widget::deleteAll(['directory' => $id]);

        return $this->redirect(['index']);
    }

    /**
     * Activated widget via ajax
     *
     * @param $id string
     *
     * @return null|string
     */
    public function actionAjaxActivate($id)
    {
        $model = new Widget(['scenario' => 'activate']);
        if ($model->load(Yii::$app->request->post())) {
            $configPath = $this->_dir . $id . '/config/main.php';
            $config = require($configPath);

            // Set attribute of model
            $model->setAttributes($config);
            $model->setAttributes([
                'directory' => $id,
                'config' => Json::encode($model->config),
                'order' => Widget::find()->where(['location' => $model->location])->count(),
            ]);

            if ($model->save()) {
                return $this->renderPartial('_active', [
                    'active' => $model,
                    'available' => [$model->directory => $config],
                ]);
            }
        }

        return null;
    }

    /**
     * Update activated widget via ajax.
     *
     * @param $id integer
     */
    public function actionAjaxUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->config = Json::encode($model->config);
            $model->save();
        }
    }

    /**
     * Delete active widget via ajax.
     *
     * @param $id integer
     */
    public function actionAjaxDelete($id)
    {
        $this->findModel($id)->delete();
    }

    /**
     * Save order for widget.
     */
    public function actionAjaxSaveOrder()
    {
        if ($ids = Yii::$app->request->post('ids')) {
            foreach ($ids as $order => $id) {
                $this->findModel($id)->updateAttributes(['order' => $order]);
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (in_array($this->action->id, ['ajax-activate', 'ajax-update', 'ajax-delete', 'ajax-save-order'])) {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)) {
            $this->_dir = Yii::getAlias('@widgets/');
            $this->_tmp = Yii::getAlias('@common/tmp/widgets/');

            return true;
        }

        return false;
    }

    /**
     * Finds the Widget model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return Widget the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Widget::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/widget/_active.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form ActiveForm */
/* @var $active common\models\Widget */
/* @var $available [] */
?>
<?php $form = ActiveForm::begin([
    'id' => 'widget-active-form-' . $active->id,
    'action' => Url::to(['/site/forbidden']),
    'options' => [
        'class' => 'widget-active-form box box-solid box-default collapsed-box',
        'data-url' => Url::to(['ajax-update', 'id' => $active->id]),
        'data-id' => $active->id,
    ],
]) ?>

<div class="box-header with-border">
    <h3 class="box-title"><?= $active->title ?></h3>

    <div class="box-tools pull-right">
        <a href="#" data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></a>
        <?= Html::button('<i class="fa fa-times"></i>', [
            'class' => 'ajax-delete-widget-btn btn btn-box-tool',
            'data' => ['url' => Url::to(['ajax-delete', 'id' => $active->id])],
        ]) ?>

    </div>
</div>
<div class="box-body widget-configuration">

    <?php if (isset($available[$active->directory]['page'])): ?>
        <?= $this->renderFile($available[$active->directory]['page'], [
            'widget' => $active,
            'form' => $form,
        ]) ?>
    <?php else: ?>
        <?= $this->render('_form', [
            'widget' => $active,
            'form' => $form,
        ]) ?>
    <?php endif ?>

</div>
<div class="box-footer">
    <button class="btn btn-flat btn-default btn-sm" type="submit"><?= Yii::t('app', 'Save') ?></button>
</div>
<?php $form::end() ?>

backend/views/widget/_available.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $available [] */
/* @var $spaces [] */

$index = 0;
$sizeofAvailable = sizeof($available);
$divideAvailable = round($sizeofAvailable / 2);
?>
<?php foreach ($available as $directory => $widget): ?>
    <?php if ($index == 0 || $index == $divideAvailable): ?>
        <div class="col-sm-12 col-md-6">
    <?php endif ?>

    <div id="available-widget-<?= $directory ?>" class="available-widget box box-solid collapsed-box">
        <div class="box-header">
            <h3 class="box-title"><?= ArrayHelper::getValue($widget, 'title') ?></h3>

            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                <?= Html::a('<i class="fa fa-times"></i>', ['delete', 'id' => $directory], [
                    'class' => 'btn btn-box-tool',
                    'data' => [
                        'method' => 'post',
                        'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    ],
                ]) ?>

            </div>
        </div>

        <?php if ($widgetDescription = ArrayHelper::getValue($widget, 'description')): ?>
            <?= Html::tag('div', $widgetDescription, ['class' => 'box-body']) ?>
        <?php endif ?>

        <?php $form = ActiveForm::begin([
            'id' => 'widget-available-form-' . $directory,
            'action' => Url::to(['/site/forbidden']),
            'options' => [
                'data-url' => Url::to(['ajax-activate', 'id' => $directory]),
                'class' => 'widget-available-form box-footer',
            ],
        ]) ?>

        <div class="input-group">
            <?= Html::dropDownList(
                'Widget[location]',
                null,
                ArrayHelper::map($spaces, 'location', 'title'),
                ['class' => 'input-sm form-control widget-location']
            ) ?>

            <div class="input-group-btn">
                <button type="submit" class="btn btn-flat btn-sm btn-default">
                    <?= Yii::t('app', 'Activate') ?>

                </button>
            </div>
        </div>
        <?php ActiveForm::end() ?>

    </div>

    <?php if ($index == $divideAvailable - 1 || $index == $sizeofAvailable - 1): ?>
        </div>
    <?php endif ?>

    <?php $index++; ?>

<?php endforeach ?>

backend/views/widget/_form.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

/* @var $this \yii\web\View */
/* @var $form \yii\bootstrap\ActiveForm */
/* @var $widget \common\models\Widget */

/**
 * Render widget config.
 *
 * @param $form   \yii\widgets\ActiveForm
 * @param $model  \common\models\Widget
 * @param $config array
 * @param $oldKey null|array
 */
$renderConfig = function ($form, $model, $config, $oldKey = null) use (&$renderConfig) {
    echo '<ul>';

    foreach ($config as $key => $value) {
        echo '<li>';
        if (is_array($value)) {
            $renderConfig($form, $model, $value, $oldKey . "[$key]");
        } else {
            echo $form->field($model, "config" . $oldKey . "[$key]")->textInput([
                'class' => 'form-control input-sm',
                'value' => $value,
                'readonly' => $key === 'class' ? 'readonly' : null,
            ])->label($key);
        }
        echo '</li>';
    }

    echo '</ul>';
};

$renderConfig($form, $widget, $widget->getConfig());

backend/views/widget/_space.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $available [] */
/* @var $active [] */
/* @var $spaces [] */

$index = 0;
$sizeofSpaces = sizeof($spaces);
$divideSpaces = round($sizeofSpaces / 2);
?>
<?php foreach ($spaces as $space): ?>
    <?php if ($index == 0 || $index == $divideSpaces): ?>
        <div class="col-sm-12 col-md-6">
    <?php endif ?>

    <div id="widget-space-<?= ArrayHelper::getValue($space, 'location') ?>"
         class="widget-space box collapsed-box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><?= ArrayHelper::getValue($space, 'title') ?></h3>

            <div class="box-tools pull-right">
                <button data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></button>
            </div>
        </div>
        <div class="box-body">

            <?php if ($spaceDescription = ArrayHelper::getValue($space, 'description')): ?>
                <p><?= $spaceDescription ?></p>
            <?php endif ?>

            <div class="widget-order">

                <?php if (isset($active[$space['location']])): ?>
                    <?php foreach ($active[$space['location']] as $widget): ?>
                        <?= $this->render('_active', [
                            'available' => $available,
                            'active' => $widget,
                        ]) ?>
                    <?php endforeach ?>
                <?php endif ?>

            </div>
        </div>
        <?php $form = ActiveForm::begin([
            'action' => Url::to(['/site/forbidden']),
            'options' => [
                'class' => 'widget-order-form box-footer',
                'data' => ['url' => Url::to(['ajax-save-order'])],
            ],
        ]) ?>

        <?= Html::hiddenInput('Widget[order]', null, ['class' => 'widget-order-field']) ?>

        <?= Html::submitButton(Yii::t('app', 'Save Order'), ['class' => 'btn btn-flat btn-success btn-block']) ?>

        <?php $form::end() ?>

    </div>

    <?php if ($index == $divideSpaces - 1 || $index == $sizeofSpaces - 1): ?>
        </div>
    <?php endif ?>

    <?php $index++ ?>

<?php endforeach ?>

backend/views/widget/create.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use yii\bootstrap\Nav;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Widget */
/* @var $errors array */

$this->title = Yii::t('app', 'Add New Widget');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Widgets'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="widget-create">
    <div id="nav-tabs-custom" class="nav-tabs-custom">
        <?= Nav::widget([
            'items' => [
                [
                    'label' => '<i class="fa fa-upload"></i> ' . Yii::t('app', 'Upload New Widget'),
                    'options' => ['class' => 'active'],
                ],
            ],
            'encodeLabels' => false,
            'options' => ['class' => 'nav-tabs nav-theme', 'id' => 'nav-theme'],
        ]) ?>

        <div class="tab-content">
            <?php $form = ActiveForm::begin([
                'id' => 'widget-create-form',
                'options' => ['enctype' => 'multipart/form-data'],
            ]) ?>

            <?= $form->field($model, 'file')->fileInput() ?>

            <?php foreach ($errors as $error): ?>
                <div class="help-block"><?= $error ?></div>
            <?php endforeach; ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Upload'), ['class' => 'btn btn-flat btn-primary']) ?>

            </div>
            <?php ActiveForm::end() ?>

        </div>
    </div>
</div>

backend/views/widget/index.php
<?php
/**
 * @link http://www.anilchaudhari.com.np/
 * @author Anil Chaudhari <imanilchaudhari@gmail.com>
 * @copyright Copyright (c) 2016 Anil Chaudhari
 * @license http://www.anilchaudhari.com.np/license/
 */

use backend\assets\WidgetAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $active [] */
/* @var $available [] */
/* @var $spaces [] */

$this->title = Yii::t('app', 'Widgets');
$this->params['breadcrumbs'][] = $this->title;
WidgetAsset::register($this);
?>
<div class="row">
    <div class="col-sm-push-6 col-md-push-5 col-sm-6 col-md-7">
        <div class="row">
            <?= $this->render('_space', [
                'active' => $active,
                'available' => $available,
                'spaces' => $spaces,
            ]) ?>
        </div>
    </div>
    <div class="col-sm-pull-6 col-md-pull-7 col-sm-6 col-md-5">
        <h4><?= Yii::t('app', 'Available Widgets') ?></h4>

        <p class="description">
            <?= Yii::t('app', 'To activate widget, click on + (plus), choose the location and click activate') ?>
        </p>
        <div class="row">
            <?= $this->render('_available', [
                'available' => $available,
                'spaces' => $spaces,
            ]) ?>
        </div>
        <div class="form-group">
            <?= Html::a(
                Yii::t('app', 'Add New Widget'),
                ['create'],
                ['class' => 'btn btn-default btn-block']
            ) ?>

        </div>
    </div>
</div>